### PR TITLE
fix slice bounds of range; add fuzzing

### LINKED ISSUE #216: composite unpack panic with runtime error: slice bounds out of range
while fuzzing, the fuzzer reports me:

```
panic: runtime error: slice bounds out of range [:193] with capacity 190 [recovered]
	panic: runtime error: slice bounds out of range [:193] with capacity 190

github.com/moov-io/iso8583/field.(*Composite).Unpack(0xc000138cf0, {0xc0000ca8e2, 0x3, 0xbe})
	/home/user/dev/opensource/iso8583/field/composite.go:266 +0x7e5
github.com/moov-io/iso8583.(*Message).Unpack(0xc00013c6e0, {0xc0000ca840, 0xa5, 0x160})
	/home/user/dev/opensource/iso8583/message.go:196 +0xa0d
```

Because, driver has to check the `offset+dataLen` is bigger than `len(data)`.

With the fix below, fuzzer is happier

```diff
diff --git a/field/composite.go b/field/composite.go
index d9a05e9..a2a54a9 100644
--- a/field/composite.go
+++ b/field/composite.go
@@ -260,6 +260,10 @@ func (f *Composite) Unpack(data []byte) (int, error) {
                isVariableLength = true
        }
 
+       if len(data) < offset+dataLen {
+               return 0, fmt.Errorf("data length: not enough data to decode. expected len %d, got %d", offset+dataLen, len(data))
+       }
+
        // data is stripped of the prefix before it is provided to unpack().
        // Therefore, it is unaware of when to stop parsing unless we bound the
        // length of the slice by the data length.
```

### PR DESCRIPTION
**Pull request by alovak**
With this PR we added fuzzing for `message.Unpack`.
The PR closes #216 and #217

### CODE REVIEW

**Review by adamdecaf — APPROVED** [review]

File: encoding/ascii.go [hunk 1]
```diff
@@ -6,7 +6,10 @@ import (
 	"github.com/moov-io/iso8583/utils"
 )
 
-var ASCII Encoder = &asciiEncoder{}
```
Comment (alovak) [inline encoding/ascii.go:9]: It's not convenient to have ASCII (and the rest) as Encoder - you can't navigate easily, etc. They can be their own types.
